name: Actualizar Portadas
on:
  schedule:
    - cron: '0 11 * * *' # 6:00 AM hora Perú (UTC-5)
  workflow_dispatch:      # Permite ejecución manual desde la pestaña Actions

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar Dependencias
        run: pip install pandas requests Pillow

      - name: Ejecutar Script de Portadas
        # Se especifica la carpeta scripts
        run: python scripts/portadas.py

      - name: Sincronizar Cambios
        run: |
          git config --global user.name "OFICIAL.PE Bot"
          git config --global user.email "bot@oficial.pe"
          # Asegura que existan las carpetas antes del add
          mkdir -p img/portadas data
          git add img/portadas/ data/portadas.csv
          git commit -m "Portadas actualizadas $(date +'%d-%m-%Y')" || echo "Sin cambios"
          git push
